### ISSUE TITLE
Unespecified error event

### ISSUE THREAD

**Issue by diegoaguilar** [lykmapipo/sails-hook-subscriber#5]
I'm using these hooks in production, I've could oftently see this errors when bootsrapping my application:

``` javascript
/home/diegoaguilar/data4/liga-fantastica/dev/api/node_modules/redis/index.js:602
                throw err;
                      ^
TypeError: Uncaught, unspecified "error" event.
    at TypeError (<anonymous>)
    at Queue.emit (events.js:74:15)
    at Worker.<anonymous> (/home/diegoaguilar/data4/liga-fantastica/dev/api/node_modules/sails-hook-subscriber/node_modules/kue/lib/kue
.js:247:18)
    at Worker.emit (events.js:98:17)
    at Worker.error (/home/diegoaguilar/data4/liga-fantastica/dev/api/node_modules/sails-hook-subscriber/node_modules/kue/lib/queue/wor
ker.js:91:10)
    at /home/diegoaguilar/data4/liga-fantastica/dev/api/node_modules/sails-hook-subscriber/node_modules/kue/lib/queue/worker.js:67:23
    at /home/diegoaguilar/data4/liga-fantastica/dev/api/node_modules/sails-hook-subscriber/node_modules/kue/lib/queue/job.js:163:59
    at try_callback (/home/diegoaguilar/data4/liga-fantastica/dev/api/node_modules/redis/index.js:592:9)
    at RedisClient.return_reply (/home/diegoaguilar/data4/liga-fantastica/dev/api/node_modules/redis/index.js:685:13)
    at HiredisReplyParser.<anonymous> (/home/diegoaguilar/data4/liga-fantastica/dev/api/node_modules/redis/index.js:321:14)
    at HiredisReplyParser.emit (events.js:95:17)
    at HiredisReplyParser.execute (/home/diegoaguilar/data4/liga-fantastica/dev/api/node_modules/redis/lib/parser/hiredis.js:43:18)
    at RedisClient.on_data (/home/diegoaguilar/data4/liga-fantastica/dev/api/node_modules/redis/index.js:547:27)
    at Socket.<anonymous> (/home/diegoaguilar/data4/liga-fantastica/dev/api/node_modules/redis/index.js:102:14)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:765:14)
```

How should I take care of it?

**Comment by lykmapipo** [comment]
@diegoaguilar 

Which redis client are you using?.

You can try [Redis Connection Settings](https://github.com/Automattic/kue#redis-connection-settings) guide for redis clients.
